### ISSUE TITLE
Some profile tips

### ISSUE THREAD

**Issue by elenajp** [ibrahimraimi/ibrahimraimi#1]
Hey Ibrahim!

Cool profile and I really love the hello world at the top of the page. I would like to offer you some tips for your profile 😀

- Since you have that cool hello world terminal banner, I would take out the 'Hello World !!!' above it as you don't need to have it twice.
- In the About Me section you mention that you are learning Django REST framework twice so I think it would be better just to mention it once.
- I would replace **I spend most of my time with coding and trying to be better day by day** with something along the lines of **I spend most of my time with coding to improve every day**. I am sure you code like a champion so you don't need to try to be better, you will be better! 🤩
- **I love connecting with different people so if you want to say hi, I'll be happy to meet you more! :)** could be something **like I love connecting with different people so if you want to say hi, I'd be happy to connect :)**

I hope this helps you. I think your profile is great and colourful! (I will check out your python project next week and look forward to it).

**Comment by ibrahimraimi** [comment]
Thanks @elenajp for the profile tips, i will do so to apply this tips
really appreciate :)

**Comment by elenajp** [comment]
You're welcome, have a great day!
